[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[constraint]]
  name = "github.com/olivere/elastic"
  branch = "release-branch.v6"

[[constraint]]
  branch = "master"
  name = "maunium.net/go/mauflag"
