package: sass
	zip -9r lindeb-firefox.zip res manifest.json save.js save.html save.css steal-authtoken.js

sass:
	../frontend/node_modules/.bin/node-sass *.sass -o .

watch:
	../frontend/node_modules/.bin/node-sass *.sass -wo .
