openapi: "3.0.0"
info:
  version: 1.0.0
  title: mau\Lu Lindeb
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: https://lindeb.maunium.net/api
paths: {}
